{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}-exporter
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pihole.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          env:
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pihole.webpasswordSecretName" . }}
                  key: webpassword
            - name: PIHOLE_HOSTNAME
              value: {{ include "exporter.targets" . }}
            - name: PORT
              value: {{ .Values.exporter.service.port | quote }}
          ports:
            - name: exporter
              containerPort: {{ .Values.exporter.service.port }}
              protocol: TCP
{{- end }}
