{{ if not .Values.auth.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  webpassword: {{ .Values.auth.password }}
{{ end }}
