---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
    {{- if .Values.headlessService.labels }}
    {{- .Values.headlessService.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.headlessService.annotations }}
  annotations:
    {{- .Values.headlessService.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector: {{- include "pihole.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-http
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
    {{- if .Values.httpService.labels }}
    {{- .Values.httpService.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.httpService.annotations }}
  annotations:
    {{- .Values.httpService.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.httpService.type }}
  ports:
    - port: {{ .Values.httpService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "pihole.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
    {{- if .Values.dnsService.labels }}
    {{- .Values.dnsService.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.dnsService.annotations }}
  annotations:
    {{- .Values.dnsService.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dnsService.type }}
  ports:
    - port: {{ .Values.dnsService.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.dnsService.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector: {{- include "pihole.selectorLabels" . | nindent 4 }}
